apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  labels:
    app: mongodb
spec:
  selector:
    app: mongodb # to map pod with service
  ports:
    - protocol: TCP
      port: 27017 # expose port
      targetPort: 27017 # container or target port
